// <auto-generated />
using System;
using FamilyPics.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyPics.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyPics.Models.Pic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName");

                    b.Property<string>("Name");

                    b.Property<int?>("UserID");

                    b.HasKey("id");

                    b.HasIndex("UserID");

                    b.ToTable("Pics");
                });

            modelBuilder.Entity("FamilyPics.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Chris",
                            UserName = "ChrisBHammond"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Bonnie",
                            UserName = "BonnieBHammond"
                        });
                });

            modelBuilder.Entity("FamilyPics.Models.Pic", b =>
                {
                    b.HasOne("FamilyPics.Models.User")
                        .WithMany("UserPics")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
